[package]
name = "mailtui"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.26"
crossterm = "0.29"
imap = { version = "3.0.0-alpha.15" }
native-tls = "0.2"
oauth2 = { version = "4", features = ["reqwest"] }
tiny_http = "0.11"
open = "3"
url = "2"
